# Generated by Django 4.2.16 on 2024-09-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=200)),
                ('Birthdate', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.IntegerField()),
                ('Skype', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience_present', models.CharField(max_length=500)),
                ('Role', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Exp_past', models.CharField(max_length=200)),
                ('Role_past', models.CharField(max_length=200)),
                ('Designation_past', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_year', models.CharField(max_length=200)),
                ('Bachelor', models.CharField(max_length=200)),
                ('Bachelor_college', models.CharField(max_length=200)),
                ('pl_year', models.CharField(max_length=200)),
                ('Plustwo', models.CharField(max_length=200)),
                ('Plustwo_school', models.CharField(max_length=200)),
                ('hs_year', models.CharField(max_length=200)),
                ('Highschool', models.CharField(max_length=200)),
                ('high_school', models.CharField(max_length=200)),
            ],
        ),
    ]
